### ISSUE TITLE
Illegal EIP712 signature for signTypedData

### ISSUE THREAD

**Issue by chzyer** [MetaMask/eth-ledger-bridge-keyring#151]
Hi, there.

We are receiving some illegal EIP712 signatures from the ledger wallet, the v is 0 or 1. As we know, v should be 27 or 28 as a valid EIP712 signature.

So I'm checking the source code as follows:
https://github.com/MetaMask/eth-ledger-bridge-keyring/blob/9a87fac6b135fe63f8f6a1291cc1173864bea86e/index.js#L417-L430

I guest it minus 27 because it wants to recover the signer, but it forgot to return the original signature. The signature should be `return 0x${payload.r}${payload.s}${payload.v}`, not `return signature`

According to this https://github.com/MetaMask/metamask-extension/issues/10240#issuecomment-910670844, I found some projects also have this issue.
* https://github.com/poap-xyz/poap-fun/pull/62
* https://github.com/gallery-so/go-gallery/pull/164

So I think maybe we can fix the root cause?

**Comment by xiaohanzhu** [comment]
Any plan to fix this bug?

**Comment by mcmire** [comment]
It appears that this bug was fixed in #152. We will issue a new release soon.

**Comment by cryptoKevinL** [comment]
Is this fix in for Ledger Live or for the Ledger/Metamask Integration?  We are having the issue as well
