### ISSUE TITLE
Ledger nano S can`t interact with Eth2 Staking Smart Contract (Metamask)

### ISSUE THREAD

**Issue by gradoj** [MetaMask/eth-ledger-bridge-keyring#49]
Ledger Live Version and Operating System
tested on Ledger Live Ledger nano X, firmware 1.2.4-5 , ETH 1.6.1
Platform and version: Windows 10
Expected behavior
Actual behavior
Steps to reproduce the behavior
Ledger cannot interact with the Eth2 SmartContrat (launchpad), the contract is not signed.

Contract data: Allow contract data in transactions -> Allowed
Ledger nano X,
Firmware 1.2.4-5 , 
App ETH 1.6.1
I have tried with different browsers, with Brave, Chrome + Metamask and with another usb cable.

the problem is happening to many people with the latest firmware.

MetaMask - RPC Error: Error: TransportStatusError: Ledger device: Condition of use not satisfied (denied by the user?) (0x6985) {code: -32603, message: "Error: TransportStatusError: Ledger device: Condit… use not satisfied (denied by the user?) (0x6985)", stack: "Error: Error: TransportStatusError: Ledger device:… use not satisfied (denied by the user?) (0x6985)"}

https://github.com/LedgerHQ/app-ethereum/issues/116

There is already a PR and has been for months 
https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/45

**Comment by Gudahtt** [comment]
Thanks for the report! Can you verify whether this is working now?

We've merged #53 (the successor to #45), so it seems possible that this is now fixed.

**Comment by gradoj** [comment]
no i cannot verify. that ship has sailed

**Comment by Gudahtt** [comment]
Ok, well thanks anyway for reporting this! Since I believe this is fixed, I'll close this for now.

**Comment by romainrbr** [comment]
Hello,

This doesn't seem to be fixed, getting the same exact issue when trying to interact with the deposit contract :+1: 
```
"Error: TransportStatusError: Ledger device: Condition of use not satisfied (denied by the user?) (0x6985)"
```

Is this related to https://github.com/MetaMask/metamask-extension/issues/9510 ?
