### ISSUE TITLE
Ledger dependencies bump to 5.36.0

### ISSUE THREAD

**Issue by ApolloUnicorn** [MetaMask/eth-ledger-bridge-keyring#50]
LedgerHQ has [released 5.36.0](https://www.npmjs.com/search?q=%40ledgerhq) of all dependencies which includes support for chainIDs above 108. Please bump dependencies on https://github.com/MetaMask/eth-ledger-bridge-keyring/tree/gh-pages . CC @brunobar79

**Comment by Andrew-Pohl** [comment]
+1 on this. We are unable to sign transactions on fuse network (ID 122) and after speaking to the ledger guys they suspect it is the same issue that @ApolloUnicorn is having.

**Comment by btchip** [comment]
Bumping to 5.43.0 should fix all remaining issues (https://github.com/LedgerHQ/ledgerjs/commit/bab3188bf5168f9e6f0f883e3b6dabc2e534537b)

**Comment by Andrew-Pohl** [comment]
> Bumping to 5.43.0 should fix all remaining issues ([LedgerHQ/ledgerjs@bab3188](https://github.com/LedgerHQ/ledgerjs/commit/bab3188bf5168f9e6f0f883e3b6dabc2e534537b))

Thanks for the update! 🤞.  @Gudahtt can we get a build with this new ledger version?
